name: Unity WebGL Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: actions/setup-unity@v1
      with:
        version: 2022.2.1f1
        license: requested

    - name: Build Unity project
      run: |
        unity-editor-version 2022.2.1f1 \
        -batchmode \
        -executeMethod WebGLBuilder.PerformBuild \
        -quit

    - name: Upload WebGL build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WebGLBuild
        path: Build/WebGL

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release $(date +'%Y-%m-%d')
        draft: false
        prerelease: false
        artifacts: Build/WebGL
