name: Unity WebGL Build

on:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y fuse libfuse2
          sudo modprobe -v fuse 
          sudo addgroup fuse
          sudo adduser $USER fuse

          sudo apt-get install --reinstall at-spi2-core

      - name: Create annotation for build error
        run: echo "::notice::Fuse installed"

    # - name: Upload WebGL build artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: WebGLBuild
    #     path: Build/WebGL

    # - name: Create GitHub Release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ env.TAG_NAME }}
    #     release_name: Release $(date +'%Y-%m-%d')
    #     draft: false
    #     prerelease: false
    #     artifacts: Build/WebGL
